name: PDFFusion
options:
  bundleIdPrefix: com.pdffusion
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic
    PRODUCT_BUNDLE_IDENTIFIER: com.pdffusion.app

targets:
  PDFFusion:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: PDFFusion
        type: group
    settings:
      base:
        INFOPLIST_KEY_CFBundleDisplayName: "PDF Fusion"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 PDF Fusion. All rights reserved."
        PRODUCT_NAME: "PDF Fusion"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: PDFFusion/PDFFusion.entitlements
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 4
        MARKETING_VERSION: 1.0.4
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_PREVIEWS: YES
    entitlements:
      path: PDFFusion/PDFFusion.entitlements
